# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
apiVersion: v2
name: lfx-v2-ui
description: A Helm chart for LFX v2 UI - Angular SSR application with Express backend
type: application
version: 0.3.1
appVersion: "latest"
keywords:
  - lfx
  - project-control-center
  - ui
home: https://github.com/linuxfoundation/lfx-v2-ui
sources:
  - https://github.com/linuxfoundation/lfx-v2-ui
